config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :restaurants do
    resources :reviews
  end
  root 'restaurants#index'

end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  has_many :reviews
  has_many :users, through: :reviews
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :restaurant
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :reviews
  has_many :restaurants, through: :reviews
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  # before_action :authenticate_user! ←よく間違える
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :full_name
    devise_parameter_sanitizer.for(:account_update) << :full_name
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]

  # GET /restaurants
  # GET /restaurants.json
  def index
    @restaurants = Restaurant.all
  end

  # GET /restaurants/1
  # GET /restaurants/1.json
  def show
  end

  # GET /restaurants/new
  def new
    @restaurant = Restaurant.new
  end

  # GET /restaurants/1/edit
  def edit
  end

  # POST /restaurants
  # POST /restaurants.json
  def create
    @restaurant = Restaurant.new(restaurant_params)

    respond_to do |format|
      if @restaurant.save
        format.html { redirect_to @restaurant, notice: 'Restaurant was successfully created.' }
        format.json { render :show, status: :created, location: @restaurant }
      else
        format.html { render :new }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /restaurants/1
  # PATCH/PUT /restaurants/1.json
  def update
    respond_to do |format|
      if @restaurant.update(restaurant_params)
        format.html { redirect_to @restaurant, notice: 'Restaurant was successfully updated.' }
        format.json { render :show, status: :ok, location: @restaurant }
      else
        format.html { render :edit }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /restaurants/1
  # DELETE /restaurants/1.json
  def destroy
    @restaurant.destroy
    respond_to do |format|
      format.html { redirect_to restaurants_url, notice: 'Restaurant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_restaurant
      @restaurant = Restaurant.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def restaurant_params
      params.require(:restaurant).permit(:name, :tel, :address, :url, :image)
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_restaurant, only: [:new, :show, :edit, :destroy, :update]
  before_action :set_review, only: [:edit, :destroy, :update]

  def new
    @review = Review.new
  end

  def create
    @review = Review.new(
      restaurant_id: params[:restaurant_id],
      user_id:       current_user.id,
      body:          review_params["body"],
      score:         review_params["score"],
    )
    @review.save
    redirect_to restaurant_url(@review.restaurant)
  end

  def edit
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.find(params[:id])
  end

  def update
    @review.update(review_params)
    @review.save
    redirect_to restaurant_url(@review.restaurant)
  end

  def destroy
    restaurant_id = @review.restaurant_id
    @review.destroy
    redirect_to restaurant_url(restaurant_id)
  end

  private

  def review_params
    params.require(:review).permit(:body, :score)
  end

  def set_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

  def set_review
    @review = Review.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse-menu">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">スパルタ食べログ</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="navbar-collapse-menu">
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><%= current_user.full_name %>さん</li>
          <li><%= link_to "設定変更", edit_user_registration_path %></li>
          <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "新規登録", new_user_registration_path %></li>
          <li><%= link_to "ログイン", new_user_session_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SpartaTabelog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
  <!-- <link href="/assets/lib/css/3-col-portfolio.css" rel="stylesheet"> -->
  <!-- Optional theme -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css">
  <!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
</head>
<body>

<%= render partial: 'layouts/header' %>

<div class="container">

  <% if notice.present? %>
    <div class="alert alert-dismissable alert-success">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <p><%= notice %></p>
    </div>
  <% end %>

  <% if alert.present? %>
    <div class="alert alert-dismissable alert-danger">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <p><%= alert %></p>
    </div>
  <% end %>
  
  <%= yield %>
</div>

</body>
</html>

app/views/restaurants/_form.html.erb
<%= form_for(@restaurant) do |f| %>
  <% if @restaurant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@restaurant.errors.count, "error") %> prohibited this restaurant from being saved:</h2>

      <ul>
      <% @restaurant.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :tel %><br>
    <%= f.text_field :tel %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.text_field :image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/restaurants/edit.html.erb
<h1>Editing Restaurant</h1>

<%= render 'form' %>

<%= link_to 'Show', @restaurant %> |
<%= link_to 'Back', restaurants_path %>

app/views/restaurants/index.html.erb
<h1>レストラン一覧</h1>

<table class="table table-striped">
<tbody>
  <% @restaurants.each do |restaurant| %>
  <tr>
    <td><img src="<%= restaurant.image %>" alt="" width="100"></td>
    <td>
      <%= restaurant.name %>
    </td>
    <td>
      <%= link_to '詳細をみる', restaurant, class: "btn btn-default" %>
    </td>
<!--<td><%= link_to 'Edit', edit_restaurant_path(restaurant) %></td>
      <td><%= link_to 'Destroy', restaurant, method: :delete, data: { confirm: 'Are you sure?' } %></td> -->
    </div>
  </div>
  <% end %>
</tbody>

</table>
<%= link_to 'New Restaurant', new_restaurant_path %>

app/views/restaurants/new.html.erb
<h1>New Restaurant</h1>

<%= render 'form' %>

<%= link_to 'Back', restaurants_path %>

app/views/restaurants/show.html.erb
<div class="main">
  <img src=" <%= @restaurant.image %>" alt="">
</div>
<h1><%= @restaurant.name %></h1>

<table class="table table-striped">
  <tr>
    <th>住所</th>
    <td><%= @restaurant.address %></td>
  </tr>
  <tr>
    <th>電話番号</th>
    <td><%= @restaurant.tel %></td>
  </tr>
  <tr>
    <th>URL</th>
    <td>
      <a href="<%= @restaurant.url %>" target="_blank">
        <%= @restaurant.url %>
      </a>
    </td>
  </tr>
  <tr>
    <th>評価</th>
    <td><%= @restaurant.reviews.average(:score) %></td>
  </tr>
</table>

<%= link_to '編集する', edit_restaurant_path(@restaurant) %>
<%= link_to 'レビューを書く', new_restaurant_review_path(@restaurant) %>


<h2>レビュー一覧</h2>
<% @restaurant.reviews.each do |review| %>
  <div>
    <%= simple_format(review.body) %>
  </div>

  <p>
    <span><%= review.score %></span>
    by <%= review.user.full_name %>
  <% if current_user == review.user %>
    <%= link_to 'レビューを編集', edit_restaurant_review_path(@restaurant, review.id) %> |
    <%= link_to 'レビューを削除', restaurant_review_path(@restaurant, review.id), method: :delete %>
  <% end %>
  </p>

  <hr>
<% end %>

<p>
  <%= link_to '一覧へ戻る', restaurants_path, class: "" %>
</p>

app/views/reviews/_form.html.erb
<%= form_for ([@restaurant, @review]) do |f| %>
  <div class="form-group">
    <%= f.label :body, 'レビュー' %><br>
    <%= f.text_area :body, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :score, 'スコア' %>：
    <%= f.radio_button(:score, '1') %>
    <%= f.radio_button(:score, '2') %>
    <%= f.radio_button(:score, '3') %>
    <%= f.radio_button(:score, '4') %>
    <%= f.radio_button(:score, '5') %>
  </div>
  <%= f.submit %>
<% end %>

app/views/reviews/edit.html.erb
<div class="row">
  <div class="col-lg-12">
    
  </div>
</div>

<%= render 'form' %>

app/views/reviews/new.html.erb
<div class="row">
  <div class="col-lg-12">
    
  </div>
</div>

<%= render 'form' %>